import { NewShiftFormSchemaType } from '@/schema/shiftSchema';

import type { GroupBase } from 'react-select';

export type OptionTypeGlobal = { label: string; value: string };
export type SelectGroup = GroupBase<OptionTypeGlobal>;
type patientData = Record<string, string>;
export type NewShiftSchemaType = Omit<NewShiftFormSchemaType, 'serviceType'> & {
  id?: number | string; // Auto-generated by IndexedDB or from server
  tempId?: number; // Auto-generated by IndexedDB
  orgName: string;
  serviceType: string | null;
  synced: number;
  patient?: patientData;
};

export type UpdatedShiftType = {
  modifiedVisits: NewShiftSchemaType[];
  deletedVisits: { id: string }[];
};

export interface InfinitePageResponse<T> {
  rows: T[];
  total: number;
  hasMore: boolean;
}

export interface InfiniteQueryResponse<T> {
  pages: InfinitePageResponse<T>[];
  pageParams: number[];
}

export type CreateUserSchemaType = {
  email: string;
  firstName: string;
  lastName: string;
  phone?: string | undefined;
  password: string;
};


