import { NewShiftFormSchemaType } from '@/schema/shiftSchema';

import type { GroupBase } from 'react-select';

export type OptionTypeGlobal = { label?: string; value: string };
export type SelectGroup = GroupBase<OptionTypeGlobal>;
type patientData = Record<string, string>;
export type NewShiftSchemaType = Omit<NewShiftFormSchemaType, 'serviceType'> & {
  id?: number | string; // Auto-generated by IndexedDB or from server
  orgName: string;
  serviceType: string | null;
  synced: number;
  patient?: patientData;
};

export type UpdatedShiftType = {
  modifiedVisits: NewShiftSchemaType[];
  deletedVisits: { id: string }[];
};
